version: 3.0.0

services:
  remix:
    image: inkit/remix
    container_name: remix-app-prod
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3000:3000
