name: CI remix

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    name: Deploy image to docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./remix
          file: ./remix/Dockerfile
          push: true
          tags: alorin/remix-inkit:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-cloud-run:
    name: Deploy To Cloud run
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - uses: "actions/checkout@v4"
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "inkit-remix"
          image: "docker.io/alorin/remix-inkit:${{ github.sha }}"
          region: europe-west1
