name: CI Api Platform

on:
  push:
    branches:
      - master
    paths:
      - "api-platform/**"
  pull_request:
    branches:
      - master
    paths:
      - "api-platform/**"
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Api Platform CI pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          workdir: ./api-platform
          files: |
            docker-compose.yml
            docker-compose.override.yml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        working-directory: ./api-platform
        run: docker compose up --wait --no-build

      - name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost

      - name: Check API reachability
        run: curl -vk -o /dev/null https://localhost

      - name: Check PWA reachability
        run: "curl -vk -o /dev/null -H 'Accept: text/html' https://localhost"

      - name: Create test database
        working-directory: ./api-platform
        run: docker compose exec -T php bin/console -e test doctrine:database:create

      - name: Run migrations
        working-directory: ./api-platform
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit
        working-directory: ./api-platform
        run: docker compose exec -T php bin/phpunit

      - name: Doctrine Schema Validator
        working-directory: ./api-platform
        run: docker compose exec -T php bin/console -e test doctrine:schema:validate
