name: CI remix

on:
  push:
    branches:
      - master
    paths:
      - "remix/**"
  pull_request:
    branches:
      - master
    paths:
      - "remix/**"

jobs:
  ci-dev:
    name: Remix dev CI pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          workdir: ./remix
          files: |
            docker-compose.yml

      - name: Install dependencies
        working-directory: ./remix
        run: docker compose run remix npm install

      - name: Check lint
        working-directory: ./remix
        run: docker compose run remix npm run lint

      - name: Check build
        working-directory: ./remix
        run: docker compose run remix npm run build

      - name: Start service
        working-directory: ./remix
        run: docker compose up --wait --no-build

      - name: Check reachability
        # sleep to let the time for the server to start
        run: sleep 5; curl -v -o /dev/null http://localhost:3000

  ci-prod:
    name: Remix prod CI pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          workdir: ./remix
          files: |
            docker-compose.prod.yml

      - name: Start service
        working-directory: ./remix
        run: docker compose -f docker-compose.prod.yml up --wait --no-build

      - name: Check reachability
        # sleep to let the time for the server to start
        run: sleep 5; curl -v -o /dev/null http://localhost:3000
